### ISSUE TITLE
Cannot find module 'tslib'

### ISSUE THREAD

**Issue by juhaelee** [filestack/adaptive#4]
I'm currently getting the following error when I try to use adaptive:

```
Cannot find module 'tslib'
Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/client/node_modules/filestack-adaptive/build/main/tree.js:3:15)
```

**Comment by velveteer** [comment]
@juhaelee Thanks for reporting this! Can you please try the latest version, 0.2.3? It includes a patch to add tslib to the npm dependencies, because we are using `importHelpers: true` in our TypeScript config.

**Comment by juhaelee** [comment]
yup! that did it 👍
